<h3>Práce s obrázkem</h3>
<?php
$fileUploadForm = $this->fileUploadForm;
$fileUploadForm->prepare();
$fileUploadForm->setAttribute('action', $this->url('prace-s-obrazkem', array('action' => 'nahrat')));
echo $this->form()->openTag($fileUploadForm);
?>
<table>
	<tbody>
	<tr>
		<td><?= $fileUploadForm->get('file')->getLabel(); ?></td>
		<td><?= $this->formElement($fileUploadForm->get('file')); ?></td>
	</tr>
	<tr>
		<td></td>
		<td><?= $this->formSubmit($fileUploadForm->get('submit')); ?></td>
	</tr>
	</tbody>
</table>
<?= $this->form()->closeTag(); ?>

<?php if($this->images){
    $dir = $this->basePath()."/images/";
    foreach($this->images as $image){?>
	    <a rel="fancy" href="<?=$dir.$image['name']?>"><img src="<?=$dir."min/".$image['name']?>" /></a>
<?php }
} ?>
