<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Test')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath().'/css/default.css')
                        ->prependStylesheet($this->basePath().'/css/jquery.fancybox-1.3.1.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						 ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/default.js')
                        ->prependFile($this->basePath() . '/js/jquery.fancybox-1.3.1.pack.js')
                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
		<div id="header">
			<div>
				<h1>MobilBonus - Test</h1>
			</div>
		</div>
		<div id="area">
			<div id="menu">
				<a href="<?=$this->basePath()?>/prace-s-obrazkem">Práce s obrázkem</a><br />
				<a href="<?=$this->basePath()?>/databaze">Databáze</a>
			</div>
			<div id="content"><?php echo $this->content; ?></div>
			</div>
		<div id="footer">
			<div>
				2013 - Antonín Výborný
			</div>
		</div>
    </body>
</html>
